name: Package

on: push

jobs:
  build-source-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [bionic, focal, hirsute, groovy, stretch, buster]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt-get update && \
          sudo apt-get install \
            debhelper dput tcl-tls libsystemd-dev pkg-config
    - name: Determine version
      run: |
          VERSION=$(head -1 debian/changelog | sed 's/^.*([0-9]*:*\([0-9.]*\)-.*$/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Get source tarball
      run: |
          curl --silent -L "https://github.com/redis/redis/archive/${VERSION}.tar.gz" -o redis_${VERSION}.orig.tar.gz
    - name: Build source package
      run: |
          tar --extract --gunzip --file redis_${VERSION}.orig.tar.gz
          cp -pr debian redis-${VERSION}
          sed -i "s/@RELEASE@/${{ matrix.dist }}/g" redis-${VERSION}/debian/changelog
          ( cd redis-${VERSION} && dpkg-buildpackage -S )
    - name: Upload source package artifact
      uses: actions/upload-artifact@v2
      with:
        name: source-${{ matrix.dist }}
        path: |
            *.debian.tar.*
            *.dsc
            redis_*.orig.tar.gz

  build-binary-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [bionic, focal, hirsute, groovy, stretch, buster]
        arch: [amd64, arm64, armhf]
    needs: build-source-package
    steps:
    - uses: actions/checkout@v2
    - name: Setup GPG key
      run: |
          mkdir -m 0700 -p ~/.gnupg
          echo "$GPG_SIGNING_KEY" | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - name: Install dependencies
      run: |
          sudo apt-get update && \
          sudo apt-get install \
            sbuild \
            debhelper dput tcl-tls libsystemd-dev pkg-config
          sudo sbuild-adduser $USER
    - name: Prepare sbuild environment
      run: sudo ./setup_sbuild.sh ${{ matrix.dist }}
    - name: Get source package
      uses: actions/download-artifact@v2
      with:
        name: source-${{ matrix.dist }}
    - name: Build binary package
      run: |
          sudo sbuild --host ${{ matrix.arch }} --dist ${{ matrix.dist }} *.dsc
    - name: Upload binary package artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-${{ matrix.dist }}-${{ matrix.arch }}
        path: |
          *.deb

  upload-packages:
    env:
      DEB_S3_VERSION: "0.11.3"
      APT_S3_BUCKET: "redislabs-yossi-test"
    runs-on: ubuntu-latest
    needs: build-binary-package
    steps:
    - name: Setup GPG key
      run: |
          mkdir -m 0700 -p ~/.gnupg
          echo "$GPG_SIGNING_KEY" | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - name: Get binary packages
      uses: actions/download-artifact@v2
    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
          ruby-version: "2.7"
    - name: Install deb-s3
      run: |
          curl -sLO https://github.com/deb-s3/deb-s3/releases/download/${{ env.DEB_S3_VERSION }}/deb-s3-${{ env.DEB_S3_VERSION }}.gem
          gem install deb-s3-${{ env.DEB_S3_VERSION }}.gem
    - name: Upload packages
      run: |
        for dir in binary-*; do \
            dist=$(echo $dir | cut -d- -f 2) ; \
            deb-s3 upload \
                --bucket ${{ env.APT_S3_BUCKET }} \
                --codename $dist \
                --sign \
                --prefix deb \
                $dir/*.deb ; \
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.APT_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.APT_S3_SECRET_ACCESS_KEY }}
